"""Event subscription endpoints for Dapr Pub/Sub.

Implements: 009-dapr-pubsub-events spec - Subscription Handlers
Provides endpoints for Dapr to deliver events to the application.

Error Handling (Phase 7):
- 200 OK: Event processed successfully (Dapr ACK)
- 500 Error: Transient failure (Dapr will retry)
- Malformed data: Log and return 200 (no retry for bad data)
- Circular triggers: Detected via source field, skipped with 200
"""
import logging
from typing import List, Dict, Any

from fastapi import APIRouter, Request, Depends, HTTPException, status, Response
from sqlmodel.ext.asyncio.session import AsyncSession

from app.database import get_session
from app.events.handlers import (
    handle_task_created,
    handle_task_updated,
    handle_task_completed,
    handle_task_deleted,
    handle_reminder_scheduled,
    handle_reminder_triggered,
    _is_handler_generated,
    _validate_event_data,
    log_dlq_alert,
    HANDLER_SOURCE
)

logger = logging.getLogger(__name__)

router = APIRouter(tags=["events"])


@router.get("/dapr/subscribe")
async def dapr_subscribe() -> List[Dict[str, Any]]:
    """Return list of topic subscriptions for Dapr.

    Dapr calls this endpoint on startup to discover subscriptions.

    Returns:
        List of subscription configurations
    """
    return [
        {
            "pubsubname": "kafka-pubsub",
            "topic": "tasks",
            "route": "/api/events/tasks",
            "metadata": {
                "deadLetterTopic": "tasks-dlq"
            }
        },
        {
            "pubsubname": "kafka-pubsub",
            "topic": "reminders",
            "route": "/api/events/reminders"
        }
    ]


@router.post("/api/events/tasks")
async def handle_task_event(
    request: Request,
    response: Response,
    session: AsyncSession = Depends(get_session)
) -> Dict[str, str]:
    """Handle all task-related events from Dapr Pub/Sub.

    Event Types:
    - task.created: New task created
    - task.updated: Task fields updated
    - task.completed: Task completion toggled
    - task.deleted: Task deleted

    Error Handling (Phase 7):
    - 200 OK: Event processed successfully or skipped (Dapr ACK)
    - 500: Transient failure (Dapr will retry with exponential backoff)
    - Malformed data: Logged and ACKed (return 200, no retry)
    - Circular triggers: Skipped (return 200, events from handlers ignored)

    Args:
        request: FastAPI request containing CloudEvent
        response: FastAPI response for setting status code
        session: Database session

    Returns:
        {"status": "ok"} on success, {"status": "error"} on failure
    """
    event_id = "unknown"
    event_type = "unknown"

    try:
        event = await request.json()
        event_type = event.get("type", "unknown")
        event_id = event.get("id", "unknown")
        event_source = event.get("source", "")
        data = event.get("data", {})

        logger.info(f"Received {event_type} event: {event_id} from {event_source}")

        # Phase 7: Circular trigger prevention (009-046)
        # Skip events generated by handlers to prevent infinite loops
        if _is_handler_generated(event_source):
            logger.info(f"Skipping handler-generated event {event_id} to prevent circular trigger")
            return {"status": "ok", "message": "handler-generated event skipped"}

        # Phase 7: Validate required fields (009-045)
        required_fields = ["task_id", "user_id"]
        if not _validate_event_data(data, required_fields):
            logger.warning(f"Malformed event data in {event_id}, acknowledging without retry")
            return {"status": "ok", "message": "malformed data acknowledged"}

        # Route to appropriate handler
        if event_type == "task.created":
            result = await handle_task_created(data, event_id, session)
        elif event_type == "task.updated":
            result = await handle_task_updated(data, event_id, session)
        elif event_type == "task.completed":
            result = await handle_task_completed(data, event_id, session)
        elif event_type == "task.deleted":
            result = await handle_task_deleted(data, event_id, session)
        else:
            logger.warning(f"Unknown task event type: {event_type}")
            return {"status": "ok", "message": "unknown event type ignored"}

        # Commit any database changes made by handlers
        await session.commit()

        return {"status": "ok"}

    except Exception as e:
        logger.error(f"Error processing task event {event_id}: {e}")
        await session.rollback()

        # Phase 7: Return 500 to trigger Dapr retry (009-044)
        response.status_code = status.HTTP_500_INTERNAL_SERVER_ERROR
        return {"status": "error", "message": str(e)}


@router.post("/api/events/reminders")
async def handle_reminder_event(
    request: Request,
    response: Response,
    session: AsyncSession = Depends(get_session)
) -> Dict[str, str]:
    """Handle all reminder-related events from Dapr Pub/Sub.

    Event Types:
    - reminder.scheduled: Reminder was scheduled
    - reminder.triggered: Reminder fired (create notification)

    Error Handling (Phase 7):
    - 200 OK: Event processed successfully (Dapr ACK)
    - 500: Transient failure (Dapr will retry)
    - Malformed data: Logged and ACKed (return 200)

    Args:
        request: FastAPI request containing CloudEvent
        response: FastAPI response for setting status code
        session: Database session

    Returns:
        {"status": "ok"} on success, {"status": "error"} on failure
    """
    event_id = "unknown"
    event_type = "unknown"

    try:
        event = await request.json()
        event_type = event.get("type", "unknown")
        event_id = event.get("id", "unknown")
        data = event.get("data", {})

        logger.info(f"Received {event_type} event: {event_id}")

        # Phase 7: Validate required fields (009-045)
        required_fields = ["task_id", "user_id"]
        if not _validate_event_data(data, required_fields):
            logger.warning(f"Malformed reminder event data in {event_id}, acknowledging without retry")
            return {"status": "ok", "message": "malformed data acknowledged"}

        # Route to appropriate handler
        if event_type == "reminder.scheduled":
            result = await handle_reminder_scheduled(data, event_id, session)
        elif event_type == "reminder.triggered":
            result = await handle_reminder_triggered(data, event_id, session)
        else:
            logger.warning(f"Unknown reminder event type: {event_type}")
            return {"status": "ok", "message": "unknown event type ignored"}

        await session.commit()

        return {"status": "ok"}

    except Exception as e:
        logger.error(f"Error processing reminder event {event_id}: {e}")
        await session.rollback()

        # Phase 7: Return 500 to trigger Dapr retry (009-044)
        response.status_code = status.HTTP_500_INTERNAL_SERVER_ERROR
        return {"status": "error", "message": str(e)}
