"""JWT authentication middleware for FastAPI."""
import jwt
import os
from fastapi import HTTPException, Depends
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from dotenv import load_dotenv

load_dotenv()

security = HTTPBearer()

BETTER_AUTH_SECRET = os.getenv("BETTER_AUTH_SECRET")
if not BETTER_AUTH_SECRET:
    raise ValueError("BETTER_AUTH_SECRET environment variable is not set")


async def verify_jwt(
    credentials: HTTPAuthorizationCredentials = Depends(security)
) -> str:
    """
    Verify JWT token and extract user_id.

    This middleware function validates JWT tokens generated by Better Auth
    on the frontend. It checks the token signature using the shared secret
    and extracts the authenticated user's ID.

    Args:
        credentials: HTTP Bearer token from Authorization header

    Returns:
        user_id (str): Authenticated user's ID from JWT payload

    Raises:
        HTTPException 401: If token is invalid, expired, or missing user_id
    """
    token = credentials.credentials

    try:
        # Decode and verify JWT signature
        payload = jwt.decode(
            token,
            BETTER_AUTH_SECRET,
            algorithms=["HS256"]
        )

        # Extract user_id (Better Auth may use "user_id" or "sub")
        user_id = payload.get("user_id") or payload.get("sub")

        if not user_id:
            raise HTTPException(
                status_code=401,
                detail="Invalid token: missing user_id"
            )

        return user_id

    except jwt.ExpiredSignatureError:
        raise HTTPException(
            status_code=401,
            detail="Token expired, please log in again"
        )
    except jwt.InvalidTokenError:
        raise HTTPException(
            status_code=401,
            detail="Invalid or malformed token"
        )
    except Exception as e:
        # Log error server-side, return generic message
        print(f"JWT verification error: {e}")
        raise HTTPException(
            status_code=401,
            detail="Authentication failed"
        )


def generate_jwt(user_id: str, email: str, name: str) -> str:
    """
    Generate JWT token for authenticated user.

    This function creates a JWT token with user information that will be
    validated by verify_jwt() middleware on protected endpoints.

    Args:
        user_id: User's unique identifier
        email: User's email address
        name: User's display name

    Returns:
        str: Signed JWT token
    """
    import datetime

    payload = {
        "user_id": user_id,
        "sub": user_id,  # Standard JWT subject claim
        "email": email,
        "name": name,
        "iat": datetime.datetime.utcnow(),
        "exp": datetime.datetime.utcnow() + datetime.timedelta(days=7)
    }

    token = jwt.encode(payload, BETTER_AUTH_SECRET, algorithm="HS256")
    return token
